### ISSUE TITLE
Improve user feedback when we failed to parse a file

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vuetify#147]
When we failed a load of file we do not give clear feedback as to why the file was not able to be loaded. If it's missing a field or it's incomplete etc etc we should be more clear about what failed in the parsing if possible. The buckets that I can think of would be file too old or from unsupported version of inspect, missing data or improperly formatted etc,... Mainly this will help us when the users come back with issues or questions so that they can give us better insight into the problem they're having.

**Comment by Mitriol** [comment]
This is not, to my knowledge, possible with current quicktypes code. Sorry

**Comment by ejaronne** [comment]
Relates to https://github.com/mitre/inspecjs/issues/13
Right now, because this error passes from inspecjs, the response to *any* error is 
"Unable to convert inspec json output. Please verify it's from an up-to-date version of the program!"

This error doesn't make sense to the user when uploading heimdall_tools jsons
So, perhaps if Heimdall Vuetify can distinguish an InSpec json vs another source, then if from InSpec use the above, but anything else use:
"Error reading in json. Please verify it came from a recent version of InSpec or heimdall_tools."
