### ISSUE TITLE
Standardize counting across toolchains for results

### ISSUE THREAD

**Issue by rx294** [mitre/heimdall-vuetify#57]
1. any kind of error -> Profile Error
2. impact 0 -> N/A (except if #1)
3. has any failed tests -> Fail whole control (except if #1 or #2)
4. has skip and pass -> Pass whole control (except if #1 or #2)
5. all tests within a control pass -> Pass (except if #1 or #2)
6. only skips -> Requires Manual Review (except if #1 or #2)

@ejaronne @aaronlippold

**Comment by Mitriol** [comment]
What about: 
7. No results? (no error)

**Comment by Mitriol** [comment]
And am I correct in interpreting "Not Reviewed" is now becoming "Requires Manual Review"?

**Comment by ejaronne** [comment]
Re: 7. no results I'd say that's a profile error

**Comment by ejaronne** [comment]
Just stick with Not Reviewed, as it is (can only be tested manually or disabled test)

**Comment by ejaronne** [comment]
any kind of error -> Profile Error
impact 0 -> N/A (except if #1)
**waived -> N/A**
has any failed tests -> Fail whole control (except if #1 or #2)
has skip and pass -> Pass whole control (except if #1 or #2)
all tests within a control pass -> Pass (except if #1 or #2)
only skips -> Requires Manual Review (except if #1 or #2)

**Comment by aaronlippold** [comment]
@rx294 @ejaronne what needs to done to close this issue?

**Comment by ejaronne** [comment]
(json samples may be sensitive, so I emailed them separately)
inspec results jsons whose counts are off relative to Heimdall Lite and Heimdall Server:

aws-ami-results.json HV error counts different from HL,HS

cis-results.json For HL and HS, Test 1.18 has an error in one of its tests, but for HV it is listed as a fail:
"ERROR     Test: Policy iam_master_policy should be attached to role "iam-master-role-name"     Message: undefined method `include?' for nil:NilClass
Exception: NoMethodError"

cms_postgres_overlay_sample.json HV error counts MUCH higher than HL,HS

cms-ars-3.1-high-microsoft-sql-server-2014-instance-stig-overlay.json - error counts off

iis-server-baseline.json HV error counts different from HL,HS
iis-site-baseline.json HV error counts different from HL,HS

overlay-microsoft-iis-site-stig-baseline.json HV error counts different from HL,HS

postgres_overlay.json and rhel7-ece-results.json - counted many many profile errors - more than the number of controls? Profile Error counts should be at the control level, not every error. One or more errors within a particular control only counts as 1 addition to the "Profile Error" bucket.

rhel-ami-nt-results.json - HV flags 2 items as errors "No describe blocks were run in this control.", but these are listed as N/A in HL and HS. With impact zero, this could actually jumped over any describe blocks. Granted, it isn't well contained, but just because  describe block isn't run isn't a reason to call it an error, per se:

           any kind of error -> Profile Error
           impact 0 -> N/A (except if #1)
           waived -> N/A
           has any failed tests -> Fail whole control (except if #1 or #2)
           has skip and pass -> Pass whole control (except if #1 or #2)
           all tests within a control pass -> Pass (except if #1 or #2)
           only skips -> Requires Manual Review (except if #1 or #2) (edited) 

rhel7ami_09042018.json - counted 2 items as Fails instead of N/As.

**Comment by Mitriol** [comment]
any exception in results -> Profile Error
impact 0 -> N/A (except if #1)
waived -> N/A
no results -> Profile Error
has any failed tests -> Fail whole control (except if #1 or #2)
has skip and pass -> Pass whole control (except if #1 or #2)
all tests within a control pass -> Pass (except if #1 or #2)
only skips -> Requires Manual Review (except if #1 or #2)

**Comment by ejaronne** [comment]
Change step 1 to:

"1. if backtrace is not null in results array -> Profile Error"

why: many exceptions are just noise. we've determined that only when a backtrace should we bucket to a profile error at this time.

from heimdall-lite:

if (result.backtrace != null) {
--
  | result.status = 'error';

**Comment by Mitriol** [comment]
Updating previous post due to new findings of how HL handles. Specifically, 0 impact trumps empty results array.

Conditions are checked in order:
    any exception in results array -> Profile Error
    waived or impact 0 -> N/A (except if #1)
    empty results array -> Profile Error (Except if #2) 
    has any failed tests -> Failed (except if #1-3)
    has skip(s) and at least one pass -> Passed whole control (except if #1-4)
    all tests within a control pass -> Passed (except if #1-5)
    only skips -> Not Reviewed (except if #1-6)

**Comment by ejaronne** [comment]
As of 11/3 build, remaining inconsistencies I found were these. (see email for json set):
aws-ami-results.json: HL/HS count 2 profile errors. HV still counts 54.
cms_postgres_overlay_sample.json: HL/HS show zero N/A and 10 errors. HV shows 1 N/A and 89 errors.
postgres_overlay.json: HL/HS show 1 N/A and 5 errors. HV shows 2 N/A and 89 errors.
rhel7-ece-results.json: HL/HS show 24 N/A and 10 errors. HV shows 48 N/A and 226 errors.
rhel7-ece-results2.json: HL/HS show 24 N/A and 10 errors. HV shows 48 N/A and 226 errors.
rhel-ami-merge-results.json: HL/HS show 35 N/A and 9 errors. HV shows 70 N/A and 214 errors.
rhel-ami-merge-results_old.json: HL/HS show 24 N/A and 10 errors. HV shows 48 N/A and 226 errors.
rhel-ami-results-cms-overlay-cms-master.json: HL/HS show 37 N/A and NO errors. HV shows 74 N/A and 203 errors.
